SchoolAD/Areas/Discente/Controllers/AcademicoController.cs
using SchoolAD.Data;
using SchoolAD.Data.DAL.Discente;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using Modelo.Discente;
using System.IO;
using System.Threading.Tasks;

namespace SchoolAD.Areas.Disciplinas.Controllers
{
    [Area("Discente")]
    public class AcademicoController : Controller
    {
        private readonly Context _context;
        private IHostingEnvironment _env;
        private readonly AcademicoDAL academicoDAL;

        public AcademicoController(Context context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;
            academicoDAL = new AcademicoDAL(context);
        }

        public async Task<IActionResult> Index()
        {
            return View(await academicoDAL.ObterAcademicosClassificadosPorNome().ToListAsync());
        }

        private async Task<IActionResult> ObterVisaoAcademicoPorId(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var academico = await academicoDAL.ObterAcademicoPorId((long)id);
            if (academico == null)
            {
                return NotFound();
            }

            return View(academico);
        }

        public async Task<IActionResult> Details(long? id)
        {
            return await ObterVisaoAcademicoPorId(id);
        }

        public async Task<IActionResult> Edit(long? id)
        {
            return await ObterVisaoAcademicoPorId(id);
        }

        public async Task<IActionResult> Delete(long? id)
        {
            return await ObterVisaoAcademicoPorId(id);
        }

        // GET: Instituicao/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,RegistroAcademico,Nascimento")] Academico academico)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await academicoDAL.GravarAcademico(academico);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Não foi possível inserir os dados.");
            }
            return View(academico);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long? id, [Bind("AcademicoID,Nome,RegistroAcademico,Nascimento")] Academico academico, IFormFile foto, string chkRemoverFoto)
        {
            if (id != academico.AcademicoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var stream = new MemoryStream();
                if (chkRemoverFoto == null)
                {
                    academico.Foto = null;
                } else
                {
                    await foto.CopyToAsync(stream);
                    academico.Foto = stream.ToArray();
                    academico.FotoMimeType = foto.ContentType;
                }
                try
                {
                    await academicoDAL.GravarAcademico(academico);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await AcademicoExists(academico.AcademicoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(academico);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long? id)
        {
            var academico = await academicoDAL.EliminarAcademicoPorId((long)id);
            TempData["Message"] = "Acadêmico " + academico.Nome.ToUpper() + " foi removida";
            return RedirectToAction(nameof(Index));
        }

        public async Task<FileContentResult> GetFoto(long id)
        {
            Academico academico = await academicoDAL.ObterAcademicoPorId(id);
            if (academico != null)
            {
                return File(academico.Foto, academico.FotoMimeType);
            }
            return null;
        }

        public async Task<FileResult> DownloadFoto(long id)
        {
            Academico academico = await academicoDAL.ObterAcademicoPorId(id);
            string nomeArquivo = "Foto" + academico.AcademicoID.ToString().Trim() + ".jpg";
            FileStream fileStream = new FileStream(System.IO.Path.Combine(_env.WebRootPath, nomeArquivo), FileMode.Create, FileAccess.Write);
            fileStream.Write(academico.Foto, 0, academico.Foto.Length);
            fileStream.Close();

            IFileProvider provider = new PhysicalFileProvider(_env.WebRootPath);
            IFileInfo fileInfo = provider.GetFileInfo(nomeArquivo);
            var readStream = fileInfo.CreateReadStream();
            return File(readStream, academico.FotoMimeType, nomeArquivo);
        }

        private async Task<bool> AcademicoExists(long? id)
        {
            return await academicoDAL.ObterAcademicoPorId((long)id) != null;
        }
    }
}

SchoolAD/Areas/Discente/Views/Academico/Create.cshtml
@model Modelo.Discente.Academico
@{
    Layout = "_LayoutIES";
}

<div class="card-block">
    <br/><div class="text-center h1">Registrando um novo acadêmico</div>
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistroAcademico" class="control-label"></label>
                <input asp-for="RegistroAcademico" class="form-control" />
                <span asp-validation-for="RegistroAcademico" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nascimento" class="control-label"></label>
                <input asp-for="Nascimento" class="form-control" />
                <span asp-validation-for="Nascimento" class="text-danger"></span>
            </div>
            <div class="form-group text-center h3">
                <input type="submit" value="Registrar Acadêmico" class="btn btn-light" />
                <a asp-action="Index" class="btn btn-info">Retornar à listagem de acadêmicos</a>
            </div>
        </form>
    </div>
    <div class="card-footer bg-dark text-center text-white">
        Informe os dados acima e/ou clique em um dos botões de ação
    </div>
</div>

@section ScriptPage {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolAD/Areas/Discente/Views/Academico/Details.cshtml
@model Modelo.Discente.Academico
@{
    Layout = "_LayoutIES";
}

@section styles {
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
}

<div class="card-block">
    <br/><div class="text-center h1">Exibindo um acadêmico existente</div>

    <div class="card-body">
        <div class="row">
            <div class="col-9">
                <div class="form-group">
                    <label asp-for="AcademicoID" class="control-label"></label>
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fa fa-key" aria-hidden="true"></i>
                        </span>
                        <input asp-for="AcademicoID" class="form-control" disabled="disabled" />
                    </div>
                    <label asp-for="RegistroAcademico" class="control-label"></label>
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fa fa-address-card-o" aria-hidden="true"></i>
                        </span>
                        <input asp-for="RegistroAcademico" class="form-control" disabled="disabled" />
                    </div>
                    <label asp-for="Nome" class="control-label"></label>
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        </span>
                        <input asp-for="Nome" class="form-control" disabled="disabled" />
                    </div>
                    <label asp-for="Nascimento" class="control-label"></label>
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="fa fa-address-card-o" aria-hidden="true"></i>
                        </span>
                        <input asp-for="Nascimento" class="form-control" disabled="disabled" />
                    </div>
                </div>
            </div>
            <div class="col-3">
                <img class="img-thumbnail" src="@Url.Action("GetFoto", "Academico", new { id = Model.AcademicoID })" style="display:block; margin-left:auto;margin-right:auto;" />
                @Html.ActionLink("Download", "DownloadFoto", "Academico", new { id = Model.AcademicoID }, null)
            </div>
        </div>
    </div>
    <div class="card-footer bg-info text-center text-white">
        <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model.AcademicoID">Alterar</a> |
        <a asp-action="Index" class="btn btn-warning">Retornar à listagem de acadêmicos</a>
    </div>
</div>

SchoolAD/Areas/Discente/Views/Academico/Edit.cshtml
@model Modelo.Discente.Academico
@{
    Layout = "_LayoutIES";
}

<div class="card-block">
    <br/><div class="text-center h1">Alterando um acadêmico existente</div>
        <div class="card-body">
            <div class="row">
                <div class="col-9">
                    <form enctype="multipart/form-data" asp-action="Edit">
                        <input type="hidden" asp-for="AcademicoID" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="RegistroAcademico" class="control-label"></label>
                            <input asp-for="RegistroAcademico" class="form-control" />
                            <span asp-validation-for="RegistroAcademico" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control" />
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nascimento" class="control-label"></label>
                            <input asp-for="Nascimento" class="form-control" />
                            <span asp-validation-for="Nascimento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Foto</label>
                            <input type="file" name="foto" class="form-control" />
                        </div>
                        <div class="form-group text-center h3">
                            <input type="submit" value="Atualizar Acadêmico" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-warning">Retornar à listagem de acadêmicos</a>
                        </div>
                    </form>
                </div>

                <div class="col-3">
                    <img class="img-thumbnail" src="@Url.Action("GetFoto", "Academico", new { id = Model.AcademicoID })" style="display:block; margin-left:auto;margin-right:auto;" />
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="chkRemoverFoto" value="Sim">Remover Foto
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer bg-info text-center text-white">
            Informe os dados acima e/ou clique em um dos botões de ação
        </div>
    </div>
@section ScriptPage {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolAD/Areas/Discente/Views/Academico/Index.cshtml
@model IEnumerable<Modelo.Discente.Academico>
@{
    Layout = "_LayoutIES";
}

@section styles {
    <link rel="stylesheet" href="~/lib/datatables/media/css/jquery.dataTables.min.css" />
}

@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}

<div class="card-block">
    <br/><div class="text-center h1">Acadêmicos Registrados</div>
    <div class="card-body">
        <table id="tabela_academicos">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.RegistroAcademico)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nascimento)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.RegistroAcademico)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nascimento)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.AcademicoID">Editar</a> |
                            <a asp-action="Details" asp-route-id="@item.AcademicoID">Visualizar</a> |
                            <a asp-action="Delete" asp-route-id="@item.AcademicoID">Excluir</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer bg-success text-center">
        <a asp-action="Create" class="btn-success">Criar um novo acadêmico</a>
    </div>
</div>


@section ScriptPage {
    <script type="text/javascript" src="~/lib/datatables/media/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#tabela_academicos').DataTable({
                "order": [[1, "asc"]]
            });
        });
    </script>
}